###
# Get Books data
###
GET http://localhost:4004/odata/v4/book-shop/Books


###
# Get Authors data
###
GET http://localhost:4004/odata/v4/book-shop/Authors

###
# Create Author
###
POST http://localhost:4004/odata/v4/book-shop/Authors
Content-Type: application/json

{"authorName": "J.K.Rowling", "address": "France","A_ID":"4","pincode":678765}


##
# Get Top-rated Book
##
GET http://localhost:4004/odata/v4/book-shop/getPopularBook()

# ###
# # Rate Book
# ###
# POST http://localhost:4004/odata/v4/book-shop/rateBook
# Content-Type: application/json

#     {
#         "bookID": "1", 
#         "rating": 10
#     }